# Generated by Django 4.2.2 on 2023-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_coin_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(default='None', max_length=35),
        ),
    ]
