# Generated by Django 4.2.2 on 2023-06-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_coin_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
    ]
