# Generated by Django 4.2.2 on 2023-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_coin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='country',
            field=models.CharField(default='', max_length=35),
        ),
    ]
