# Generated by Django 4.2.2 on 2023-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_coin_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='alloy',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
