# Generated by Django 4.2.2 on 2023-06-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_coin_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
