# Generated by Django 4.2.2 on 2023-06-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_delete_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='country',
            field=models.CharField(choices=[('DOM', 'Dominican Republic'), ('USA', 'United States')], default='DOM', max_length=35),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('user', models.CharField(max_length=35)),
                ('comment', models.TextField(max_length=500)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
            ],
        ),
    ]
