# Generated by Django 4.2.2 on 2023-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_coin_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='condition',
            field=models.CharField(choices=[('M', 'Mint State'), ('G', 'Good'), ('F', 'Fair'), ('P', 'Poor')], default='M', max_length=1),
        ),
    ]
