# Generated by Django 4.2.2 on 2023-06-11 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_bid_user_alter_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 20, 34, 16, 922700, tzinfo=datetime.timezone.utc)),
        ),
    ]
