# Generated by Django 4.2.2 on 2023-06-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_bid_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.TextField(default='../static/images/default-coin-img.gif', max_length=300)),
                ('institution', models.CharField(choices=[('PCGS', 'Profesional Coin Granding Service'), ('NGC', 'Numismatic Guaranty Company'), ('ANACS', 'American Numismatic Association')], default='PCGS', max_length=10)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
