# Generated by Django 4.2.2 on 2023-06-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='certifications',
            field=models.ManyToManyField(to='main_app.certification'),
        ),
    ]
